version: "3"

x-minecraft: &mc
  image: itzg/minecraft-server:java17-alpine
  expose:
    - "25565"
  tty: true
  stdin_open: true
  restart: unless-stopped
  networks:
    - minecraft

x-minecraft-environment: &mc-env
  EULA: "TRUE"
  OVERRIDE_SERVER_PROPERTIES: "TRUE"
  SYNC_CHUNK_WRITES: "false"
  USE_AIKAR_FLAGS: "TRUE"
  OPS: CeciliaSanare,DaggerDoc
  OVERRIDE_OPS: "TRUE"
  REMOVE_OLD_MODS: "TRUE"
  REMOVE_OLD_MODS_INCLUDE: "*.jar"
  REMOVE_OLD_MODS_DEPTH: 1
  REMOVE_OLD_MODS_EXCLUDE: ""

x-minecraft-whitelist: &mc-env-wl
  WHITELIST: "CeciliaSanare,DaggerDoc,_MRCY"
  ENFORCE_WHITELIST: "TRUE"
  OVERRIDE_WHITELIST: "TRUE"

services:
  infrared:
    container_name: infrared
    image: haveachin/infrared:latest
    ports:
      - "25565:25565/tcp"
    expose:
      - "25565"
    networks:
      - minecraft
    volumes:
      - ${INFRARED_DIR}:/configs
    restart: unless-stopped
  
  minecraft-smp:
    <<: *mc
    container_name: minecraft-smp
    environment:
      <<: *mc-env
      VERSION: 1.19.2
      TYPE: PAPER
      SPIGET_RESOURCES: 64346,91722
      ICON: https://raw.githubusercontent.com/cecilia-sanare/SelfHosted/main/Icons/smp.png
      OVERRIDE_ICON: "TRUE"
      MOTD: Polycule SMP Server
    volumes:
      - /etc/minecraft/latest/smp:/data
  
  minecraft-atm:
    <<: *mc
    container_name: minecraft-atm
    environment:
      <<: *mc-env
      MEMORY: 16G
      TYPE: FORGE
      VERSION: 1.18.2
      FORGEVERSION: 40.1.68
      GENERIC_PACK: /modpacks/ATM_7_Server_0.4.29.zip
      MOTD: Polycule ATM7 Server
    volumes:
      - /etc/minecraft/latest/atm:/data
      - /etc/minecraft/modpacks:/modpacks:ro

  minecraft-origins:
    <<: *mc
    container_name: minecraft-origins
    environment:
      <<: *mc-env
      <<: *mc-env-wl
      MEMORY: 8G
      TYPE: FABRIC
      VERSION: 1.19.2
      GENERIC_PACKS: "TemmiesOriginsServerConfig-0.1.0,/modpacks/TemmiesOriginsServer-0.1.0"
      GENERIC_PACKS_PREFIX: "/modpacks/"
      GENERIC_PACKS_SUFFIX: ".zip"
      MOTD: Polycule Origins Server
      ICON: https://raw.githubusercontent.com/cecilia-sanare/SelfHosted/main/Icons/origins.png
      OVERRIDE_ICON: "TRUE"
      SEED: "2830351026098010116"
    volumes:
      - /etc/minecraft/latest/origins:/data
      - /etc/minecraft/modpacks:/modpacks:ro

networks:
  minecraft: {}