name: Deploy

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 5 * * *'

jobs:
  main:
    name: Deploy
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.event.head_commit.message, 'emergency(') || github.event_name == 'schedule' }}
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.SSH_HOST }}
          username: minecraft
          password: ${{ secrets.SSH_PASSWORD }}
          script_stop: true
          script: |
            export RUNTIME_GH_TOKEN=${{ secrets.RUNTIME_GH_TOKEN }}
            git -C SelfHosted fetch && git -C SelfHosted reset --hard origin/main || git clone https://github.com/cecilia-sanare/SelfHosted.git
            (cd SelfHosted && ./setup.sh)