name: Deploy

on:
  schedule:
    - cron: '0 5 * * *'

jobs:
  main:
    name: Nightly
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.10.0
        with:
          access_token: ${{ github.token }}
      - name: Deploy
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.SSH_HOST }}
          username: minecraft
          password: ${{ secrets.SSH_PASSWORD }}
          script_stop: true
          script: |
            git -C SelfHosted fetch && git -C SelfHosted reset --hard origin/main || git clone https://github.com/cecilia-sanare/SelfHosted.git
            (cd SelfHosted && ./setup.sh)